# BigQuery Configuration

GCP_PROJECT_ID = "lateral-client-509315-s1"

BIGQUERY_SOURCE_PROJECT= "bigquery-public-data"
BIGQUERY_DATASET= "thelook_ecommerce"

# Snowflake Configuration
SNOWFLAKE_DATABASE = "DB_ERP"
SNOWFLAKE_WAREHOUSE = "DEV_WH"
SNOWFLAKE_ROLE = "ROLE_DEV"
SNOWFLAKE_BRONZE_SCHEMA = "BRONZE"
SNOWFLAKE_SILVER_SCHEMA = "SILVER"
SNOWFLAKE_GOLD_SCHEMA = "GOLD"
