--TRUNCATE TABLE DB_ERP.BRONZE.DISTRIBUTION_CENTERS;
--TRUNCATE TABLE DB_ERP.BRONZE.INVENTORY_ITEMS;
--TRUNCATE TABLE DB_ERP.BRONZE.ORDER_ITEMS;
--TRUNCATE TABLE DB_ERP.BRONZE.PRODUCTS;
--TRUNCATE TABLE DB_ERP.BRONZE.USERS;

select * from db_erp.bronze.distribution_centers