--TRUNCATE TABLE DB_ERP.BRONZE.DISTRIBUTION_CENTERS;
--TRUNCATE TABLE DB_ERP.BRONZE.INVENTORY_ITEMS;
--TRUNCATE TABLE DB_ERP.BRONZE.ORDER_ITEMS;
--TRUNCATE TABLE DB_ERP.BRONZE.PRODUCTS;
--TRUNCATE TABLE DB_ERP.BRONZE.USERS;

--select * from db_erp.bronze.ORDER_ITEMS limit 3;

select * from db_erp.bronze.DISTRIBUTION_CENTERS